"""
Application configuration and settings.
"""

import logging
import secrets
from typing import List

from cryptography.fernet import Fernet
from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    # Application
    APP_NAME: str = "Infinite Gist"
    API_V1_STR: str = "/api/v1"

    # Security
    SECRET_KEY: str = Field(default_factory=lambda: secrets.token_urlsafe(48))
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 60 * 24 * 8  # 8 days
    ALGORITHM: str = "HS256"

    # Database
    DATABASE_URL: str = "sqlite:///./infinite_gist.db"

    # GitHub OAuth
    GITHUB_CLIENT_ID: str = ""
    GITHUB_CLIENT_SECRET: str = ""
    GITHUB_AUTHORIZATION_URL: str = "https://github.com/login/oauth/authorize"
    GITHUB_TOKEN_URL: str = "https://github.com/login/oauth/access_token"
    GITHUB_API_BASE_URL: str = "https://api.github.com"
    GITHUB_REDIRECT_URI: str = "http://localhost:8000/api/v1/auth/github/callback"
    GITHUB_SCOPES: List[str] = ["gist", "user:email"]
    FRONTEND_URL: str = "http://localhost:8000"

    # CORS
    BACKEND_CORS_ORIGINS: List[str] = ["http://localhost:3000", "http://localhost:8080"]

    # Phase 2: Detection settings
    TRUFFLEHOG_PATH: str = "trufflehog"
    ENABLE_TRUFFLEHOG: bool = True
    MAX_GIST_FILE_BYTES: int = 10 * 1024 * 1024
    TRIAGE_CONFIDENCE_LOW: float = 0.5
    TRIAGE_CONFIDENCE_HIGH: float = 0.7

    # Rate limiting
    GITHUB_API_RATE_LIMIT_PER_HOUR: int = 5000

    # Security settings
    ENCRYPTION_KEY: str = Field(default_factory=lambda: Fernet.generate_key().decode())
    TRUST_PROXY_HEADERS: bool = False
    COOKIE_SECURE: bool = False
    SCHEDULER_ENABLED: bool = False
    SCHEDULER_INTERVAL_SECONDS: int = 60

    # Notifications
    SMTP_HOST: str = ""
    SMTP_PORT: int = 587
    SMTP_USERNAME: str = ""
    SMTP_PASSWORD: str = ""
    SMTP_FROM_EMAIL: str = ""
    SMTP_STARTTLS: bool = True

    @field_validator("SECRET_KEY")
    @classmethod
    def validate_secret_key(cls, value: str) -> str:
        normalized = value.strip().lower()
        if len(value) < 32 or normalized.startswith(("change-this", "your-")):
            raise ValueError(
                "SECRET_KEY must be a non-placeholder value of 32+ characters"
            )
        return value

    @field_validator("ENCRYPTION_KEY")
    @classmethod
    def validate_encryption_key(cls, value: str) -> str:
        try:
            Fernet(value.encode())
        except (TypeError, ValueError) as exc:
            raise ValueError(
                "ENCRYPTION_KEY must be a Fernet key generated by Fernet.generate_key()"
            ) from exc
        return value

    model_config = SettingsConfigDict(
        case_sensitive=True, env_file=".env", extra="ignore"
    )


logger = logging.getLogger(__name__)

settings = Settings()

# Warn loudly if security-critical keys are using generated defaults.
# SECRET_KEY / ENCRYPTION_KEY are generated by a default_factory when absent,
# so they are never empty — but a freshly generated value changes on every
# restart, invalidating all existing JWTs / OAuth state tokens and making
# previously-encrypted GitHub tokens undecryptable. Production MUST set these
# in .env. Pydantic tracks values loaded from both the process environment and
# dotenv in model_fields_set; defaults are omitted from that set.
if "SECRET_KEY" not in settings.model_fields_set:
    logger.warning(
        "SECRET_KEY is not set in the environment — a random value is generated "
        "on every restart, invalidating existing JWTs and OAuth state tokens. "
        "Set SECRET_KEY in .env for any non-dev deployment."
    )
if "ENCRYPTION_KEY" not in settings.model_fields_set:
    logger.warning(
        "ENCRYPTION_KEY is not set in the environment — a random value is "
        "generated on every restart, making previously encrypted GitHub tokens "
        "undecryptable. Set ENCRYPTION_KEY in .env for any non-dev deployment."
    )
